### PR TITLE
remove OpenCV version specification to allow OpenCV 3 or 4

### PR DESCRIPTION
**Pull request by cjue**

### CODE REVIEW

**Review by simonschmeisser — CHANGES_REQUESTED** [review]
strange, I thought I replied to this ...
I'm fine with the content of this PR, it's just the commit message. The ranges you refer to would look like
`find_package(OpenCV 3.0..3.3 REQUIRED)`
I think the actual issue is that the `OpenCVConfig-version.cmake` likely claims that OpenCV 4 is not backwards compatible to OpenCV 3 and thus rejects it

**Comment by cjue** [comment]
Yes, it looks like OpenCV 4 is not accepted as a stand-in for `find_package(OpenCV 3 REQUIRED)`.

From CMake 3.19 I think it would be a valid workaround to write `find_package(OpenCV 3..4 REQUIRED)`.

Should I make a new PR with a changed commit message?

**Comment by simonschmeisser** [comment]
your commit message can also be interpreted as a preferred but unavailable solution, so ... whatever :-D

**Comment by cjue** [comment]
> your commit message can also be interpreted as a preferred but unavailable solution, so ... whatever :-D

Yeah, that's what I tried to say. I should maybe keep the commit message shorter and leave the discussion part for the PR.

**Pull request merged**
